
aws:
  region: ca-central-1
micronaut:
  application:
    name: backend
  http:
    client:
      read-timeout: 10000ms
  multitenancy:
    filter:
      enabled: true
  server:
    cors:
      enabled: true
      configurations:
        angular:
          allowed-origins:
            - "http://localhost:4200/"
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
          allow-credentials: true
  security:
    enabled: true
    authentication: idtoken
    basic-auth:
      enabled: false
    redirect:
      enabled: false
    intercept-url-map:
      - pattern: /**
        http-method: OPTIONS
        access:
          - isAnonymous()
    token:
      propagation:
        enabled: true
        service-id-regex: ".*"
      jwt:
        enabled: true
        signatures:
          jwks:
            public:
              url: https://cognito-idp.${aws.region}.amazonaws.com/${app.auth.public.pool}/.well-known/jwks.json
            admin:
              url: https://cognito-idp.${aws.region}.amazonaws.com/${app.auth.admin.pool}/.well-known/jwks.json
endpoints:
  health:
    enabled: true
    sensitive: false
app:
  auth:
    public:
      pool: "ca-central-1_PHR6msiks"
      issuer: https://cognito-idp.${aws.region}.amazonaws.com/${app.auth.public.pool}
    admin:
      pool: "ca-central-1_liR9FZX79"
      issuer: https://cognito-idp.${aws.region}.amazonaws.com/${app.auth.admin.pool}
  iot-core:
    arn-prefix: "arn:aws:iot:ca-central-1:114829892869"
  tenant:
    default: "public"
    list:
      public:
        id: "public"
        active: true
        hostname: "public.app.healthesolutions.ca"
        api-base: "https://public.app.healthesolutions.ca"
      local:
        id: "local"
        name: "Local Testing"
        active: true
        hostname: "localhost:8080"
        api-base: "http://localhost:8080"
      staging:
        id: "staging"
        name: "Staging Environment"
        active: true
        hostname: "staging.app.healthesolutions.ca"
        api-base: "https://staging.app.healthesolutions.ca"
