
aws:
  region: ca-central-1
  cognito:
    public-pool: ca-central-1_PHR6msiks
micronaut:
  application:
    name: backend
  http:
    client:
      read-timeout: 10000ms
  multitenancy:
    filter:
      enabled: true
  security:
    enabled: true
    authentication: idtoken
    basic-auth:
      enabled: false
    redirect:
      enabled: false
    token:
      propagation:
        enabled: true
        service-id-regex: ".*"
      jwt:
        enabled: true
        claims-validators:
          issuer: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.public-pool}
        signatures:
          jwks:
            cognito:
              url: https://cognito-idp.${aws.region}.amazonaws.com/${aws.cognito.public-pool}/.well-known/jwks.json
endpoints:
  health:
    enabled: true
    sensitive: false
app:
  iot-core:
    arn-prefix: "arn:aws:iot:ca-central-1:114829892869"
  tenant:
    default: "public"
    list:
      public:
        id: "public"
        active: true
        hostname: "public.app.healthesolutions.ca"
        api-base: "https://public.app.healthesolutions.ca"
      local:
        id: "local"
        name: "Local Testing"
        active: true
        hostname: "localhost:8080"
        api-base: "http://localhost:8080"
      staging:
        id: "staging"
        name: "Staging Environment"
        active: true
        hostname: "staging.app.healthesolutions.ca"
        api-base: "https://staging.app.healthesolutions.ca"