# fly.toml app configuration file generated for cabinet-mq on 2023-06-22T11:47:26-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cabinet-mq"
primary_region = "iad"

[[mounts]]
  source = "rabbitmq_data"
  destination = "/var/lib/rabbitmq/mnesia/data"

[env]
    RABBITMQ_USE_LONGNAME  = "true"

[[services]]
    internal_port = 1883
    protocol = "tcp"
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0
    [[services.ports]]
        handlers = ["tls"]
        port = 1883
    [[services.tcp_checks]]
        grace_period = "1s"

[http_service]
    internal_port = 15675
    force_https = true
    auto_stop_machines = true
    auto_start_machines = true
    min_machines_running = 0

