reverse_dns_lookups = false
mqtt.tcp_listen_options.sndbuf = 1024
mqtt.tcp_listen_options.recbuf = 1024
mqtt.tcp_listen_options.buffer = 1024
management_agent.disable_metrics_collector = true

mqtt.listeners.tcp.default = 1883
web_mqtt.tcp.port = 15675
mqtt.allow_anonymous  = false

auth_backends.1 = rabbit_auth_backend_oauth2

auth_oauth2.resource_server_id = cabinet
auth_oauth2.additional_scopes_key = mqtt
auth_oauth2.preferred_username_claims = username
auth_oauth2.default_key = id1
auth_oauth2.signing_keys.id1 = test/config_schema_SUITE_data/certs/cert.pem
auth_oauth2.algorithms.1 = RS256