name: app
description: JCT Pill Organizer App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.9.0+75

environment:
  sdk: '>=3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_platform_widgets: ^6.0.0
  flutter_svg: ^2.0.6
  intl: ^0.18.0
  http: ^0.13.4
  sleek_circular_slider: ^2.0.1
  modal_bottom_sheet: ^3.0.0-pre
  dots_indicator: ^3.0.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.6.0
  animations: ^2.0.3
  retrofit: ^4.0.1
  shared_preferences: ^2.0.15
  package_info_plus: ^4.0.1
  flutter_secure_storage: ^8.0.0
  validatorless: ^1.2.3
  firebase_core: ^2.21.0
  firebase_messaging: ^14.1.1
  flutter_local_notifications: ^14.1.0
  provider: ^6.0.4
  settings_ui: ^2.0.2
  equatable: ^2.0.5
  timezone: ^0.9.1
  flutter_timezone: ^1.0.4
  flutter_esp_ble_prov:
    path: ./flutter_esp_ble_prov
  tuple: ^2.0.1
  flutter_markdown: ^0.6.14
  flutter_blue_plus:
    path: ./flutter_blue_plus
  protobuf: ^2.1.0
  shimmer: ^3.0.0
  dio: ^5.3.3
  flutter_native_timezone: ^1.0.7
  dotted_border: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_phosphor_icons: ^0.0.1+6
  flutter_colorpicker: ^1.0.3
  firebase_crashlytics: ^3.4.3
  permission_handler: ^11.0.1
  flutter_screenutil: ^5.9.0
  pixel_perfect: any
  app_settings: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.0
  freezed: ^2.3.2
  retrofit_generator: ^7.0.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - lib/assets/SVG/share.svg
    - lib/assets/noun-open-box-1485434.svg
    - lib/assets/package-svgrepo-com.svg
    - lib/assets/SVG/moon.svg
    - lib/assets/SVG/sun.svg
    - lib/assets/SVG/moonWhite.svg
    - lib/assets/SVG/sunWhite.svg
    - lib/assets/SVG/greenlight.svg
    - lib/assets/SVG/redlight.svg
    - lib/assets/SVG/offlight.svg
    - lib/assets/SVG/cancelIcon.svg
    - lib/assets/SVG/pills/hexagon.svg
    - lib/assets/SVG/pills/round.svg
    - lib/assets/SVG/pills/triangle.svg
    - lib/assets/SVG/pills/doubleCircle.svg
    - lib/assets/SVG/pills/tear.svg
    - lib/assets/SVG/pills/square.svg
    - lib/assets/SVG/pills/pentagon.svg
    - lib/assets/SVG/pills/capsule.svg
    - lib/assets/provision-plug-in.png
    - lib/assets/base_device.png
    - lib/assets/base_bin_sprite.png
    - lib/assets/organizer.png
    - lib/assets/greenled.png
    - lib/assets/redled.png
    - lib/assets/organizer_128.png
    - lib/assets/single-pill.png
    - lib/assets/meds/CAPSULE_FG.png
    - lib/assets/meds/CAPSULE_COLOR.png
    - lib/assets/meds/DIAMOND_FG.png
    - lib/assets/meds/DIAMOND_COLOR.png
    - lib/assets/meds/OVAL_FG.png
    - lib/assets/meds/OVAL_COLOR.png
    - lib/assets/meds/RECTANGLE_FG.png
    - lib/assets/meds/RECTANGLE_COLOR.png
    - lib/assets/meds/ROUND_FG.png
    - lib/assets/meds/ROUND_COLOR.png
    - lib/assets/meds/SQUARE_FG.png
    - lib/assets/meds/SQUARE_COLOR.png
    - lib/assets/meds/UNK_FG.png
    - lib/assets/meds/UNK_COLOR.png
    - lib/assets/256w/DEV_SYM_AM.png
    - lib/assets/256w/DEV_SYM_PM.png
    - lib/assets/star_bg.png
    - lib/assets/main-icon.png
    - lib/assets/SVG/Bluetooth.svg
    - lib/assets/SVG/WifiHigh.svg
    - lib/assets/SVG/PlugsConnected.svg
    - lib/assets/SVG/Timer.svg
    - lib/assets/SVG/BellSimpleRinging.svg
    - lib/assets/SVG/Pill.svg
    - lib/assets/SVG/CheckCircle.svg
    - lib/assets/SVG/DEV_SYM_AM.svg
    - lib/assets/SVG/DEV_SYM_PM.svg
    - lib/assets/SVG/pencilLight.svg
    - lib/assets/SVG/PencilSimpleLine.svg
    - lib/assets/SVG/Globe.svg
    - lib/assets/SVG/User.svg
    - lib/assets/SVG/tabs/house-filled.svg
    - lib/assets/SVG/tabs/house-outline.svg
    - lib/assets/SVG/tabs/settings-filled.svg
    - lib/assets/SVG/tabs/settings-outline.svg
    - lib/assets/SVG/tabs/pill-filled.svg
    - lib/assets/SVG/tabs/pill-outline.svg
    - lib/assets/SVG/tabs/user-filled.svg
    - lib/assets/SVG/tabs/user-outline.svg

  fonts:
    - family: Roboto Slab
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf
        - asset: fonts/RobotoSlab-Bold.ttf
          weight: 700
        - asset: fonts/RobotoSlab-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoSlab-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

icons_launcher:
  image_path: 'lib/assets/cabinet_icon_144.png'
  platforms:
    android:
      enable: true
    ios:
      enable: true
      remove-alpha: true
