CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    user_type VARCHAR(31) NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
