CREATE TABLE users (
    id TEXT PRIMARY KEY,
    user_type TEXT NOT NULL,
    name TEXT,
    email TEXT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
